// == Types

// EventDetails : Header.js
export const CHANGE_HEART_ICON = 'CHANGE_HEART_ICON';
export const OPEN_SHARE_LINKS_MODAL = 'OPEN_SHARE_LINKS_MODAL';
export const CLOSE_SHARE_LINKS_MODAL = 'CLOSE_SHARE_LINKS_MODAL';

// User : Preferences.js
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const CHANGE_MODAL_STATUS = 'CHANGE_MODAL_STATUS';
export const CHANGE_CHECK_INPUT_VALUE = 'CHANGE_CHECK_INPUT_VALUE';
export const CHANGE_EDITOR_MODE = 'CHANGE_EDITOR_MODE';
