export default [
  {
    id: 1,
    tag: 'Angular',
    image: 'src/assets/images/test_evt.png',
    title: 'Titan Blue',
    date: '17/10',
    support: 'Twitch',
    location: 'Paris',
    price: 'Gratuit',
    content: 'Oportunum est, ut arbitror, explanare nunc causam',
  },
  {
    id: 2,
    tag: 'Angular',
    image: 'src/assets/images/test_evt.png',
    title: 'Titan Red',
    date: '17/10',
    support: 'Twitch',
    location: 'Paris',
    price: 'Gratuit',
    content: 'Oportunum est, ut arbitror, explanare nunc causam nunc',
  },
  {
    id: 3,
    tag: 'Angular',
    image: 'src/assets/images/test_evt.png',
    title: 'Titan Blue',
    date: '17/10',
    support: 'Twitch',
    location: 'Paris',
    price: 'Gratuit',
    content: 'Oportunum est, ut arbitror, explanare nunc causam',
  },
  {
    id: 4,
    tag: 'Angular',
    image: 'src/assets/images/test_evt.png',
    title: 'Orion Red',
    date: '17/10',
    support: 'Twitch',
    location: 'Paris',
    price: 'Gratuit',
    content: 'Oportunum est, ut arbitror, explanare nunc causam',
  },
  {
    id: 5,
    tag: 'Angular',
    image: 'src/assets/images/test_evt.png',
    title: 'Titan Blue',
    date: '17/10',
    support: 'Twitch',
    location: 'Paris',
    price: 'Gratuit',
    content: 'Oportunum est, ut arbitror, explanare nunc causam',
  },
  {
    id: 6,
    tag: 'Angular',
    image: 'src/assets/images/test_evt.png',
    title: 'Projets Universe',
    date: '17/10',
    support: 'Twitch',
    location: 'Paris',
    price: 'Gratuit',
    content: 'Oportunum est, ut arbitror, explanare nunc causam',
  },
];
