export default {
  event: [
    {
      title: 'Testa',
      url_image: 'a',
      price: 'gratuit',
      description: 'aaa',
      address: 'Paris',
      is_online: 'oui',
      url_live: 'a',
      nbr_like: 0,
      date_start: '01/01/2020',
      date_end: '01/01/2020',
      created_at: 'a',
      updated_at: 'a',
    },
    {
      title: 'Test2',
      url_image: 'a',
      price: 'payant',
      description: 'aaa',
      address: 'Lyon',
      is_online: 'oui',
      url_live: 'a',
      nbr_like: 0,
      date_start: '01/02/2020',
      date_end: '01/02/2020',
      created_at: 'a',
      updated_at: 'a',
    },
    {
      title: 'Test3',
      url_image: 'a',
      price: 'gratuit',
      description: 'aaa',
      address: 'Reims',
      is_online: 'non',
      url_live: 'a',
      nbr_like: 0,
      date_start: '01/02/2020',
      date_end: '02/02/2020',
      created_at: 'a',
      updated_at: 'a',
    },
  ],
  tag: [
    {
      name: 'js',
      created_at: 'a',
      updated_at: 'a',
    },
    {
      name: 'cms',
      created_at: 'a',
      updated_at: 'a',
    },
    {
      name: 'php',
      created_at: 'a',
      updated_at: 'a',
    },
  ],

};
