// == Types

// EventDetails : Header.js
export const CHANGE_HEART_ICON = 'CHANGE_HEART_ICON';
export const OPEN_SHARE_LINKS_MODAL = 'OPEN_SHARE_LINKS_MODAL';
export const CLOSE_SHARE_LINKS_MODAL = 'CLOSE_SHARE_LINKS_MODAL';

// User : Preferences.js
export const FETCH_USER_INFOS = 'FETCH_USER_INFOS';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const CHANGE_MODAL_STATUS = 'CHANGE_MODAL_STATUS';
export const CHANGE_CHECK_INPUT_VALUE = 'CHANGE_CHECK_INPUT_VALUE';
export const CHANGE_EDITOR_MODE = 'CHANGE_EDITOR_MODE';
export const SEND_UPDATE_INFO = 'SEND_UPDATE_INFO';
export const SHOW_MESSAGE_UPDATE_USER = 'SHOW_MESSAGE_UPDATE_USER';
export const DELETE_SHOW_MESSAGE = 'DELETE_SHOW_MESSAGE';


// App : Nav.js
// EventDetails : CheckButtons.js
export const OPEN_NAV_MODAL = 'OPEN_NAV_MODAL';
export const DECONNECT = 'DECONNECT';

// App : Footer.js
export const FETCH_EVENTS_BY_LOCATION = 'FETCH_EVENTS_BY_LOCATION';
export const SEND_LOCATION_SEARCH_DATA = 'SEND_LOCATION_SEARCH_DATA';


// App : Nav.js
export const ACTIVE_NAV_MENU = 'ACTIVE_NAV_MENU';
export const CHANGE_INPUT_VALUE_IN_MODAL = 'CHANGE_INPUT_VALUE_IN_MODAL';
export const CHANGE_CHECK_VALUE_IN_MODAL = 'CHANGE_CHECK_VALUE_IN_MODAL';
export const SUBMIT_REGISTER = 'SUBMIT_REGISTER';
export const EMPTY_FIELDS_REGISTER = 'EMPTY_FIELDS_REGISTER';
export const SHOW_MESSAGE_REGISTER = 'SHOW_MESSAGE_REGISTER';
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const SHOW_MESSAGE_LOGIN = 'SHOW_MESSAGE_LOGIN';
export const DO_CONNECT = 'DO_CONNECT';
export const CHECK_CONNECT = 'CHECK_CONNECT';


// Home : QuickSearchBar.js
// Events : Form.js
export const HANDLE_SEARCH_CHANGE = 'HANDLE_SEARCH_CHANGE';
export const HANDLE_SEARCH_SUBMIT = 'HANDLE_SEARCH_SUBMIT';


// Events : Form.js
export const HANDLE_FORM_CHANGE = 'HANDLE_FORM_CHANGE';
export const HANDLE_SUBMIT = 'HANDLE_SUBMIT';
export const SHOW_ADVANCED_FORM = 'SHOW_ADVANCED_FORM';
export const ADD_FILTERS = 'ADD_FILTERS';
export const ADD_ADDRESS_VALUE = 'ADD_ADDRESS_VALUE';
export const EMPTY_FORM_VALUE = 'EMPTY_FORM_VALUE';
export const FILL_FILTER_LIST = 'FILL_FILTER_LIST';
export const TEST_FILTERS_MID = 'TEST_FILTERS_MID';

// Events : Home.js
export const FETCH_NEXT_EVENTS = 'FETCH NEXT EVENTS';


// == Events Middlewares
export const TRIGGER_MIDDLEWARE = 'TRIGGER_MIDDLEWARE';
export const FETCH_REQUESTED_DATA = 'FETCH_REQUESTED_DATA';
export const ALL_EVENTS = 'ALL_EVENTS';
export const NEXT_EVENTS = 'NEXT_EVENTS';


// == Home : SearchForm.js
export const CHANGE_SEARCH_FORM_VALUE = 'CHANGE_SEARCH_FORM_VALUE';
export const EMPTY_SEARCH_FORM_VALUE = 'EMPTY_SEARCH_FORM_VALUE';
export const HANDLE_SEARCH_FORM_CHANGE = 'HANDLE_SEARCH_FORM_CHANGE';


// EventsDetails
export const GET_EVENT_DETAILS = 'GET_EVENT_DETAILS';
export const FETCH_EVENT_DETAILS = 'FETCH_EVENT_DETAILS';


// User : Update
export const CHANGE_UPDATE_USER = 'CHANGE_UPDATE_USER';

// Slider : events
export const CHANGE_LEFT_FOR_SLIDER = 'CHANGE_LEFT_FOR_SLIDER';


